### ISSUE TITLE
Next and Previous buttons

### ISSUE THREAD

**Issue by colinburns** [dnadesign/silverstripe-googlesitesearch#1]
Hey Willr,

Wondering if you have had any issues with the Next and Previous buttons for the search facility?

The first 2 clicks work okay but after that the URL encoding is getting too mixed up for the search function to understand.

/searchresults?Search=Cell+Culture - this is the initial page where the search is "Cell Culture"

When you click Next Page this is the URL

/searchresults?Search=Cell%2BCulture&start=11 [Still okay but the search has gone from Cell Culture to Cell+Culture]

If you click Previous or Next now the search facility breaks because now it is searching for 
Cell%2BCulture instead.

I don't know if this is something you have found or if perhaps I have implemented the module incorrectly.

Cheers,
Colin

**Comment by KINKCreative** [comment]
Colin, good start it just needed this to work across other entities as well:
```
//Ln 81
data.nextLink = decodeURI(qs.toString());
//Ln 88
data.previousLink = decodeURI(qs.toString());
```
