### ISSUE TITLE
Install path

### ISSUE THREAD

**Issue by clyonsEIS** [dnadesign/silverstripe-googlesitesearch#3]
The composer package installs to silverstripe-googlesitesearch by default, which breaks the js/css inclusions. 3 possible solutions:
-change js/css inclusions to refer to 'silverstripe-googlesitesearch' path instead of 'googlesitesearch'
-update composer require instructions to specify the custom dir 'googlesitesearch'
-determine the js/css inclusion path dynamically based on install

I'm not sure which of these (if any) is the best-practice solution.

**Comment by wilr** [comment]
Thanks, updated composer installer-name.
