### ISSUE TITLE
3.0 compatbility branch

### ISSUE THREAD

**Issue by svandragt** [dnadesign/silverstripe-googlesitesearch#4]
Hi Will,
I'm looking to use this module in a 3.0 site so am in the process of making it compatible I was wondering if you have a preference for branch naming? Currently I'm going with 3.0.x-1.0 but will adapt to your choice. Let me know. Cheers, Sander

**Comment by wilr** [comment]
@svandragt no actual tags or branches yet (woops) but yes make 3.0 changes and submit a PR and I'll mark that as 1.0, I'll then tag the current 3.1 supported as 1.1.0
